Vagrant.configure("2") do |config|

  # Set a box with OS
  config.vm.box = "gusztavvargadr/windows-10"

  # Disable automatic box update checking. 
  config.vm.box_check_update = false

  # Create a public network, which generally matched to bridged network.
  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  
    # Customize the amount of memory on the VM:
    # vb.memory = "4096"
  end

  # Enable provisioning with a shell script.
  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    
	# Install the .NET Core SDK
    Invoke-WebRequest -Uri https://download.visualstudio.microsoft.com/download/pr/d0348cb9-c348-4c68-93aa-70122dd44a33/5f982a6ffdb29ed70af11ffc08d3189e/dotnet-sdk-7.0.402-win-x64.exe -OutFile dotnet-sdk-7.0.402-win-x64.exe
    Start-Process -FilePath dotnet-sdk-7.0.402-win-x64.exe
    
    # Install console app package
	dotnet tool install --global --version 1.0.0 --add-source http://10.0.2.2:5000/v3/index.json --no-cache ANechytailo
    SHELL
end