Vagrant.configure("2") do |config|

  # Set a box with OS
  config.vm.box = "debian/bookworm64"

  # Disable automatic box update checking. 
  config.vm.box_check_update = false

  # Create a public network, which generally matched to bridged network.
  config.vm.network "public_network"

  # Enable provisioning with a shell script.
  config.vm.provision "shell", inline: <<-SHELL

	apt-get update
    apt-get upgrade

    wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    rm packages-microsoft-prod.deb

    sudo apt-get update && sudo apt-get install -y dotnet-sdk-7.0

	# Install console app package
    dotnet tool install --global --version 1.0.0 --add-source http://10.0.2.2:5000/v3/index.json --no-cache ANechytailo
   SHELL
end
